@host = http://localhost:4000/das/v1

###
POST {{host}}/authorizations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0

{
    "dateemmited":"2021-01-18",
    "startdate":"2021-02-3",
    "enddate":"2021-02-6",
    "resumework":"2021-12-3",
    "total_days":13,
    "pendingdays":2,
    "observation":"Ninguna",
    "authorizationsyear":"2021",
    "partida":"9088",
    "workdependency":"09cdfc58-4b8f-4ec4-b2a0-1af3474754be",
    "person":{
        "uuid": "00776805-231a-4ccf-b21b-42a3a48a682d"
    }

}

###
GET {{host}}/authorizations
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0

###
GET {{host}}/authorizations/25092ba1-f1cb-495e-8d12-43a7cde16f9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0

###
PUT {{host}}/authorizations/25092ba1-f1cb-495e-8d12-43a7cde16f9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0

{
    "dateemmited": "2021-01-29",
    "startdate": "2021-01-25",
    "enddate": "2021-02-12",
    "resumework": "2021-02-15",
    "holidays": 0,
    "total_days": 15,
    "pendingdays": 0,
    "observation": "Amonos prros2.0.1",
    "authorizationsyear": "2020",
    "partida": "57009",
    "workdependency_uuid": "34896e5c-ab18-4320-87cc-073eb7632b5f"
}


###
GET {{host}}/authorizations/pdfauthorization/25092ba1-f1cb-495e-8d12-43a7cde16f9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0