@host = http://localhost:4000/das/v1

###
POST {{host}}/authorization/emmit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

{
    "dateemmited":"2021-01-18",
    "startdate":"2021-02-3",
    "enddate":"2021-02-6",
    "resumework":"2021-12-3",
    "total_days":13,
    "pendingdays":2,
    "observation":"Ninguna",
    "authorizationyear":"2021",
    "partida":"9088",
    "workdependency":"09cdfc58-4b8f-4ec4-b2a0-1af3474754be",
    "person":{
        "uuid": "00776805-231a-4ccf-b21b-42a3a48a682d"
    }

}

###
GET {{host}}/authorization/works
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

###
GET {{host}}/authorization/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

###
POST {{host}}/authorization/works
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

{
    "name":"Esta es otra dependencia de trabajo"
}

###
POST {{host}}/authorization/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

{
    "job":"Este es un trabajo"
}

###
GET {{host}}/authorization/many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

###
GET {{host}}/authorization/one/25092ba1-f1cb-495e-8d12-43a7cde16f9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

###
PUT {{host}}/authorization/update/25092ba1-f1cb-495e-8d12-43a7cde16f9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4

{
    "dateemmited": "2021-01-29",
    "startdate": "2021-01-25",
    "enddate": "2021-02-12",
    "resumework": "2021-02-15",
    "holidays": 0,
    "total_days": 15,
    "pendingdays": 0,
    "observation": "Amonos prros2.0.1",
    "authorizationyear": "2020",
    "partida": "57009",
    "workdependency_uuid": "34896e5c-ab18-4320-87cc-073eb7632b5f"
}


###
GET {{host}}/authorization/pdfauthorization/25092ba1-f1cb-495e-8d12-43a7cde16f9f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNTA5YzIyNmEtMDFiOC00YTg0LWE5ZjMtZjI0Njg5MmU5ZTZiIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMzE1NDY0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.o3rW1-IbRNs5Jq5lVmbRJuKKvjH4rFxoWeiCdZutXXOxibM9Xt1x2svErWnvxBCS00F7XkqvUxW9qlUQA1lIZzVJRWCKbL1npys7oJMQzaqOCaGt-ULBX8RaJecsJe7vB9wl_0Of4ngLRYtnv7AQfcFOkIyZzsYwg2YGE5krlk4