@host = http://localhost:4000/das/v1

###
GET {{host}}/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

###
GET {{host}}/jobs/009174ab-704a-4893-b751-1b7e3c7907c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk


###
POST {{host}}/jobs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

{
    "job":"Este es un trabajo"
}

###
DELETE {{host}}/jobs/009174ab-704a-4893-b751-1b7e3c7907c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

###
PUT {{host}}/jobs/009174ab-704a-4893-b751-1b7e3c7907c0
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

{
    "job":"OFICINISTA II"
}

