@host = http://localhost:4000/das/v1

###
GET {{host}}/persons/40/Mynor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMTYzMzQxLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.V_Gh5R464TJR9ZjJyV9BavEZkZITqoPF3iBfMY7OYrsNy1lA5tijhobMVUrz2QFYCDkqYb_Mq969oKC33XrzwnsFy5pxiikGNWyUynzeatqGKcedz1Y15winsj8gD3QFOgw2Il1I6eOeyUwUVyNHgDl6CkDZFdm2NgM_pJ2JiBc

###
GET {{host}}/persons/3b928667-4ebd-4245-8cf4-9f21ae4d65f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMTYzMzQxLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.V_Gh5R464TJR9ZjJyV9BavEZkZITqoPF3iBfMY7OYrsNy1lA5tijhobMVUrz2QFYCDkqYb_Mq969oKC33XrzwnsFy5pxiikGNWyUynzeatqGKcedz1Y15winsj8gD3QFOgw2Il1I6eOeyUwUVyNHgDl6CkDZFdm2NgM_pJ2JiBc

###
PUT {{host}}/persons/3b928667-4ebd-4245-8cf4-9f21ae4d65f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMTYzMzQxLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.V_Gh5R464TJR9ZjJyV9BavEZkZITqoPF3iBfMY7OYrsNy1lA5tijhobMVUrz2QFYCDkqYb_Mq969oKC33XrzwnsFy5pxiikGNWyUynzeatqGKcedz1Y15winsj8gD3QFOgw2Il1I6eOeyUwUVyNHgDl6CkDZFdm2NgM_pJ2JiBc

{
    "fullname":"MYNOR RENE VELIZ C.",
    "cui":"9901359740",
    "job_uuid":"056910d1-92f5-4213-836f-6e0750c4c0e3"
}
