@host = http://localhost:4000/das/v1

###
GET {{host}}/persons?page=1&limit=100&filter=
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNDQ2MjIzLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.YKPPZ1DTKsoiyfQa_fzkQJeRwG4e-ohI3UzMSPf2zyyDZclBZBnYr-4AzLDXPWAWVZZGG5-1POIp59EvoDTIdumlSfglXH9tA7glCS99OA_Pvu0YU58F-mzH-wBhr_7en6d9tdX9AWJVmWk7LuFofEGOpK9-uYZJkZRO-p8XZU0

###
GET {{host}}/persons/3b928667-4ebd-4245-8cf4-9f21ae4d65f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNDQ2MjIzLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.YKPPZ1DTKsoiyfQa_fzkQJeRwG4e-ohI3UzMSPf2zyyDZclBZBnYr-4AzLDXPWAWVZZGG5-1POIp59EvoDTIdumlSfglXH9tA7glCS99OA_Pvu0YU58F-mzH-wBhr_7en6d9tdX9AWJVmWk7LuFofEGOpK9-uYZJkZRO-p8XZU0

###
PUT {{host}}/persons/3b928667-4ebd-4245-8cf4-9f21ae4d65f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNDQ2MjIzLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.YKPPZ1DTKsoiyfQa_fzkQJeRwG4e-ohI3UzMSPf2zyyDZclBZBnYr-4AzLDXPWAWVZZGG5-1POIp59EvoDTIdumlSfglXH9tA7glCS99OA_Pvu0YU58F-mzH-wBhr_7en6d9tdX9AWJVmWk7LuFofEGOpK9-uYZJkZRO-p8XZU0

{
    "fullname":"MYNOR RENE VELIZ C.",
    "cui":"9901359740",
    "job_uuid":"056910d1-92f5-4213-836f-6e0750c4c0e3"
}
