@host = http://localhost:4000/das/v1

###
GET {{host}}/persons/40/Mynor
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMDUzODc3LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.Oif8qAWigcHB-WJRccEB0VZsr_I90GasZJzYoTVNrl2CvCZsTSCZnpW1b2AuG5-WXxgALD23YOtPw4PJvqEiAYclQhDnbXJwsrw9L77wIZErkVByfcCcL3y58MG3E1kuZRBlNaA3OXtKa33hC9CXWzcA0Abju9_1-8VsLVHCo6Y

###
GET {{host}}/persons/3b928667-4ebd-4245-8cf4-9f21ae4d65f8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjExMDUzODc3LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.Oif8qAWigcHB-WJRccEB0VZsr_I90GasZJzYoTVNrl2CvCZsTSCZnpW1b2AuG5-WXxgALD23YOtPw4PJvqEiAYclQhDnbXJwsrw9L77wIZErkVByfcCcL3y58MG3E1kuZRBlNaA3OXtKa33hC9CXWzcA0Abju9_1-8VsLVHCo6Y