@host = http://localhost:4000/das/v1
# @host =  https://das-jalapa.herokuapp.com/das/v1

###
POST {{host}}/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0

{
    "username":"cristianJL",
    "password":"Guat33mala225"
}

###
POST {{host}}/login
Content-Type: application/json

{
    "username":"cristianJL",
    "password":"Guat33mala225"
}

###
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0


###
POST {{host}}/users/changepassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzNzMxMzI0LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.g4jJMuNsHKUUxr-sW_JdX37uif6guRHueNHJCwWJT8UDQz_V09VClrpVb-GcwJ1sZoDwXckWu9mcU6q95ltGhi2yorA1mrW-MtQIgtov-2hxNijfPdWG1aqpeDMm9sRVRJX0ZwgSIsR3bJedN_bZSRmEz9l1whXWvR9L8YvitG0

{
    "actual_password":"123456",
    "new_password":"abcde"
}

