@host = http://localhost:4000/das/v1
# @host =  https://das-jalapa.herokuapp.com/das/v1

###
POST {{host}}/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyOTYxNjY4LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.VXwq6kVoL--59gtXhYnbkuI0HbLgLpxwFlms9QDKsNcxSe5M2XZizKmCxi0hJuD4iaCsNe77_WUEPNtBxXJaYBaGtO9RlvKrDfOaLfF_Ag4rakd78CyNRnl0BucSCE5R09PobAm7f3Aor8-weIjx8n9YQcboLQzIZZSZdqWHfaw

{
    "username":"cristianJL",
    "password":"Guat33mala225"
}


###
POST {{host}}/login
Content-Type: application/json

{
    "username":"cristianJL",
    "password":"Guat33mala225"
}

###
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyOTYxNjY4LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.VXwq6kVoL--59gtXhYnbkuI0HbLgLpxwFlms9QDKsNcxSe5M2XZizKmCxi0hJuD4iaCsNe77_WUEPNtBxXJaYBaGtO9RlvKrDfOaLfF_Ag4rakd78CyNRnl0BucSCE5R09PobAm7f3Aor8-weIjx8n9YQcboLQzIZZSZdqWHfaw

###
GET {{host}}/users/rols
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyOTYxNjY4LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.VXwq6kVoL--59gtXhYnbkuI0HbLgLpxwFlms9QDKsNcxSe5M2XZizKmCxi0hJuD4iaCsNe77_WUEPNtBxXJaYBaGtO9RlvKrDfOaLfF_Ag4rakd78CyNRnl0BucSCE5R09PobAm7f3Aor8-weIjx8n9YQcboLQzIZZSZdqWHfaw

###
POST {{host}}/users/changepassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyOTYxNjY4LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.VXwq6kVoL--59gtXhYnbkuI0HbLgLpxwFlms9QDKsNcxSe5M2XZizKmCxi0hJuD4iaCsNe77_WUEPNtBxXJaYBaGtO9RlvKrDfOaLfF_Ag4rakd78CyNRnl0BucSCE5R09PobAm7f3Aor8-weIjx8n9YQcboLQzIZZSZdqWHfaw

{
    "actual_password":"123456",
    "new_password":"abcde"
}

