@host = http://localhost:4000/das/v1
# @host =  https://das-jalapa.herokuapp.com/das/v1

###
POST {{host}}/users/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNzg3NzAwLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.M5Adjy3BTHC7YXe-S_nOWPgTB6MdC9UP4715OWHl6isbASzg5x0AzOOKbaEfNycGn-PLMkZfa8jti9RfE4HQQ0ivWEkFcVfIp8y6LPUepnJXpw9Erm3JJZEnyayvJvJMalOmurD3rNZ3DIUJWSf7smlg6H--5lT8wGqCV_axG9w

{
    "username":"cristianJL",
    "password":"Guat33mala225"
}


###
POST {{host}}/login
Content-Type: application/json

{
    "username":"mike",
    "password":"abcde"
}

###
GET {{host}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNzg3NzAwLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.M5Adjy3BTHC7YXe-S_nOWPgTB6MdC9UP4715OWHl6isbASzg5x0AzOOKbaEfNycGn-PLMkZfa8jti9RfE4HQQ0ivWEkFcVfIp8y6LPUepnJXpw9Erm3JJZEnyayvJvJMalOmurD3rNZ3DIUJWSf7smlg6H--5lT8wGqCV_axG9w

###
GET {{host}}/users/rols
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNzg3NzAwLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.M5Adjy3BTHC7YXe-S_nOWPgTB6MdC9UP4715OWHl6isbASzg5x0AzOOKbaEfNycGn-PLMkZfa8jti9RfE4HQQ0ivWEkFcVfIp8y6LPUepnJXpw9Erm3JJZEnyayvJvJMalOmurD3rNZ3DIUJWSf7smlg6H--5lT8wGqCV_axG9w

###
POST {{host}}/users/changepassword
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiYzFlMjMyN2YtYWZiOS00YTY3LTk1MzUtMjIzNTQwNzZkM2YzIiwidXNlcm5hbWUiOiJtaWtlIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEyNzg3NzAwLCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.M5Adjy3BTHC7YXe-S_nOWPgTB6MdC9UP4715OWHl6isbASzg5x0AzOOKbaEfNycGn-PLMkZfa8jti9RfE4HQQ0ivWEkFcVfIp8y6LPUepnJXpw9Erm3JJZEnyayvJvJMalOmurD3rNZ3DIUJWSf7smlg6H--5lT8wGqCV_axG9w

{
    "actual_password":"123456",
    "new_password":"abcde"
}

