@host = http://localhost:4000/das/v1

###
GET {{host}}/works
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

###
GET {{host}}/works/0c8fa695-fc42-42ef-8e15-1b7df65cb1c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

###
POST {{host}}/works
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

{
    "name":"Esta es otra dependencia de trabajo"
}


###
DELETE {{host}}/works/0c8fa695-fc42-42ef-8e15-1b7df65cb1c6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

###
PUT {{host}}/works/ba1cbedb-a7ae-483e-bb74-af3cc63ef6b5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMDI2YjJiYTctMGIxNC00OTAwLWIzM2MtMTczZjI3YzIwMWJlIiwidXNlcm5hbWUiOiJjcmlzdGlhbkpMIiwicm9sIjoiYWRtaW4ifSwiZXhwIjoxNjEzODg5NDk5LCJpc3MiOiJtaW5pc3RlcmlvIGRlIHNhbHVkIn0.B9moy5IaDxrBXIZo0GUhPu2zSmbBYPmPzvCMMpQZSGgGtFEB03WI-8FeWyv-7omjTjF71d5gDHP2ExpqIrqG0mTeerKV_JfRtqP2Wgnu-Qxg3sFoTQXGSy4pSR7r2Ckq_bW3fazAWWOIlQT0vbDc4swUd5uUlQSwum0dpZx1utk

{
    "name":"Este es un trabajo actualizado otras"
}